import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import City from '../public/floating.svg'
import Clouds from '../public/clouds.svg'
import Wind from '../public/wind.svg'
import Humidity from '../public/humidity.svg'

export default function Home(data) {

  const [night, setNight] = useState();

  const toggle = () => {
    if (data.data.dt < data.data.sys.sunrise) {
      setNight(true);
    } else {
      setNight(false);
    }
  }

  useEffect(() => {
    toggle();
  })
  
  const icon = data.data.weather[0].icon;

  return (
    <div className={` ${night ? styles.night : styles.day} `}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.box}>
          <div className={styles.row1}>
            <div><Image src={Clouds} /> <span>{data.data.clouds.all}%</span></div>
            <div><Image src={Wind} /> {data.data.wind.speed}m/s</div>
            <div><Image src={Humidity}/> {data.data.main.humidity}%</div>
          </div>

          <div className={styles.temps}>
            <div className={styles.mainTemp}>{Math.round(data.data.main.temp)}</div>
            <div className={styles.tempsColumn}>
              <div className={styles.grades}>°C</div>
              <div>{Math.round(data.data.main.temp_min)}</div>
              <div>{Math.round(data.data.main.temp_max)}</div>
            </div>
          </div>

          <div className={styles.city}>
            <div>{data.data.name}, {data.data.sys.country}</div>
            <div className={styles.description}>{data.data.weather[0].description}</div>
            <div className={styles.cityImg}><Image src={`http://openweathermap.org/img/wn/${icon}@2x.png`} unoptimized='true' width={100} height={100} className={styles.cityImg} /></div>
          </div>

          <div className={styles.backImage}>
            <Image src={City} />
          </div>

        </div>

      </main>
    </div>
  )
}

export async function getStaticProps() {

  //const fetch = require('node-fetch-with-proxy');

  // Call an external API endpoint to get data.
  // You can use any data fetching library
  const res = await fetch(`https://api.openweathermap.org/data/2.5/weather?lat=32.5027&lon=-117.00371&units=metric&appid=${process.env.API}`)
  const data = await res.json();
  
  // Create a new JavaScript Date object based on the timestamp
  // multiplied by 1000 so that the argument is in milliseconds, not seconds.
  // Hours part from the timestamp
  // Minutes part from the timestamp
  // Seconds part from the timestamp

  // Will display time in 10:30:23 format

  const unix_timestamp = (unix) => {
    let unix_timestamp = unix
    let date = new Date(unix_timestamp * 1000);
    let hours = date.getHours();
    let minutes = "0" + date.getMinutes();
    let seconds = "0" + date.getSeconds();
    let formattedTime = hours + ':' + minutes.substr(-2) + ':' + seconds.substr(-2);
    return console.log(formattedTime)
  }


  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      data,
    },
  }
}
