import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.box}>

        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  // Call an external API endpoint to get data.
  // You can use any data fetching library
  const res = await fetch('https://api.openweathermap.org/data/2.5/weather?lat=32.5027&lon=-117.00371&appid=2431d269d204f0fc4f08ac1ce09df0a5')
  const data = await res.json()
  console.log(data);

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      weather,
    },
  }
}
